language: ruby
rvm:
  - 2.2.3
  - 1.9.3
  - jruby-9.1.16.0
  - jruby-1.7.27
  - rbx
  - ruby-head
  - jruby-head
before_install:
 - gem install bundler -v 1.10.5
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head
