language: ruby
rvm:
  - 2.3.5
  - 2.4.2
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
env:
  - RUBYOPT=""
  - RUBYOPT="--enable-frozen-string-literal"
