language: ruby
rvm:
  - 2.2.3
  - 1.9.3
  - jruby-9.0.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head
before_install:
 - 'if [ "$TRAVIS_RUBY_VERSION" = "jruby-9.0.0.0" ]; then rvm get head && rvm reload && rvm install $TRAVIS_RUBY_VERSION && rvm use $TRAVIS_RUBY_VERSION; fi'
 - gem install bundler -v 1.10.5
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
    - rvm: jruby-head
